// Mocks generated by Mockito 5.4.6 from annotations
// in rent_house/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rent_house/Models/property.dart' as _i3;
import 'package:rent_house/Providers/property_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PropertyProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPropertyProvider extends _i1.Mock implements _i2.PropertyProvider {
  MockPropertyProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  set properties(List<_i3.Property>? _properties) => super.noSuchMethod(
        Invocation.setter(
          #properties,
          _properties,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set favorites(List<_i3.Property>? _favorites) => super.noSuchMethod(
        Invocation.setter(
          #favorites,
          _favorites,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userProperties(List<_i3.Property>? _userProperties) => super.noSuchMethod(
        Invocation.setter(
          #userProperties,
          _userProperties,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? _isLoading) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          _isLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set errorMessage(String? _errorMessage) => super.noSuchMethod(
        Invocation.setter(
          #errorMessage,
          _errorMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set uploadProgress(double? _uploadProgress) => super.noSuchMethod(
        Invocation.setter(
          #uploadProgress,
          _uploadProgress,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedProperty(_i3.Property? _selectedProperty) => super.noSuchMethod(
        Invocation.setter(
          #selectedProperty,
          _selectedProperty,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<List<_i3.Property>> getAllPropertiesStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPropertiesStream,
          [],
        ),
        returnValue: _i4.Future<List<_i3.Property>>.value(<_i3.Property>[]),
      ) as _i4.Future<List<_i3.Property>>);

  @override
  _i4.Future<List<_i3.Property>> getHostPropertiesStream(String? hostId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHostPropertiesStream,
          [hostId],
        ),
        returnValue: _i4.Future<List<_i3.Property>>.value(<_i3.Property>[]),
      ) as _i4.Future<List<_i3.Property>>);

  @override
  _i4.Future<List<_i3.Property>> getFavoritesStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoritesStream,
          [userId],
        ),
        returnValue: _i4.Future<List<_i3.Property>>.value(<_i3.Property>[]),
      ) as _i4.Future<List<_i3.Property>>);

  @override
  _i4.Future<void> loadPropertiesOnce({
    int? page = 1,
    int? pageSize = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPropertiesOnce,
          [],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadFavorites(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #loadFavorites,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchFavorites(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #fetchFavorites,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadHostProperties(String? hostId) => (super.noSuchMethod(
        Invocation.method(
          #loadHostProperties,
          [hostId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchProperties() => (super.noSuchMethod(
        Invocation.method(
          #fetchProperties,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadAllProperties() => (super.noSuchMethod(
        Invocation.method(
          #loadAllProperties,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadMoreProperties({
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoreProperties,
          [],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void selectProperty(_i3.Property? p) => super.noSuchMethod(
        Invocation.method(
          #selectProperty,
          [p],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> toggleFavorite(_i3.Property? property) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [property],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> createProperty(
    _i3.Property? property, {
    dynamic images,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProperty,
          [property],
          {#images: images},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateProperty(
    String? id,
    _i3.Property? property, {
    dynamic newImages,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProperty,
          [
            id,
            property,
          ],
          {#newImages: newImages},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> deleteProperty(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProperty,
          [id],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> completeRental(_i3.Property? property) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeRental,
          [property],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> restoreProperty(_i3.Property? property) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreProperty,
          [property],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> addToFavorites(
    String? userId,
    String? propertyId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [
            userId,
            propertyId,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> removeFromFavorites(
    String? userId,
    String? propertyId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [
            userId,
            propertyId,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> testStorageConnection() => (super.noSuchMethod(
        Invocation.method(
          #testStorageConnection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
