name: rent_house
description: "Allô Bailleur is a comprehensive mobile app for real estate rentals in Cameroun, allowing users to search properties with advanced filters, save favorites, chat in real-time with owners, book securely, and manage listings—all powered by Firebase for seamless, real-time experiences."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^3.0.3
  state_notifier: ^1.0.0

  # UI & Utils
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar: ^4.0.1
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.10+1
  table_calendar: ^3.1.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  cloud_functions: ^6.0.4

  # Supabase
  supabase_flutter: ^2.6.0

  # Navigation
  go_router: ^17.0.0

  # Features
  image_picker: ^1.2.0
  google_maps_flutter: ^2.13.1
  google_sign_in: ^7.2.0
  permission_handler: ^12.0.1
  path: ^1.9.0

  # Payments
  flutter_stripe: ^12.1.1

  # Galerie zoomable
  photo_view: ^0.15.0

  # DEPENDENCIES
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_dotenv: ^6.0.0
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^19.5.0
  video_player: ^2.9.2
  chewie: ^1.8.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  http: ^1.2.0
  geolocator: ^14.0.2
  share_plus: ^12.0.1
  connectivity_plus: ^7.0.0
  url_launcher: ^6.2.6
  shimmer: ^3.0.0

  cross_file: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

  supabase: any
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/logo.svg
    - assets/images/house.jpeg
    - assets/images/nimish.jpg
    - assets/images/sherli7.jpg
    - assets/images/interior0.jpg
    - assets/images/interior1.jpg
    - assets/images/interior2.jpg
    - assets/images/interior3.jpg
    - assets/images/maleAvatar.png
    - assets/images/mammoth_logo.png
    - assets/images/defaultAvatar.jpg
    - .env
