// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYg4EXSH_8uKrvrG_Vfh_7dbHTFsh8oG8',
    appId: '1:40543426548:web:93896f5b4d7618ea848ba1',
    messagingSenderId: '40543426548',
    projectId: 'allobailleur-c7e9d',
    authDomain: 'allobailleur-c7e9d.firebaseapp.com',
    storageBucket: 'allobailleur-c7e9d.firebasestorage.app',
    measurementId: 'G-VHJ3N3ZJY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVy4bbxIqdTJyCLU_0ijneZcNbdYK4y4',
    appId: '1:40543426548:android:a82f4f3fdafe099a848ba1',
    messagingSenderId: '40543426548',
    projectId: 'allobailleur-c7e9d',
    storageBucket: 'allobailleur-c7e9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-hgkuSesAIIH5KZimZggnodHrrKiI6_I',
    appId: '1:40543426548:ios:daebae3934ab9363848ba1',
    messagingSenderId: '40543426548',
    projectId: 'allobailleur-c7e9d',
    storageBucket: 'allobailleur-c7e9d.firebasestorage.app',
    iosBundleId: 'com.example.rentHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-hgkuSesAIIH5KZimZggnodHrrKiI6_I',
    appId: '1:40543426548:ios:daebae3934ab9363848ba1',
    messagingSenderId: '40543426548',
    projectId: 'allobailleur-c7e9d',
    storageBucket: 'allobailleur-c7e9d.firebasestorage.app',
    iosBundleId: 'com.example.rentHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYg4EXSH_8uKrvrG_Vfh_7dbHTFsh8oG8',
    appId: '1:40543426548:web:6732fefcf9c6d9ec848ba1',
    messagingSenderId: '40543426548',
    projectId: 'allobailleur-c7e9d',
    authDomain: 'allobailleur-c7e9d.firebaseapp.com',
    storageBucket: 'allobailleur-c7e9d.firebasestorage.app',
    measurementId: 'G-YEMRFNLV2D',
  );
}
